author: SwearWord
database: false
description: Allows players to buy and sell goods on a VirtualShop.
main: ${project.groupId}.${project.name}
name: ${project.name}
startup: postworld
url: http://blockface.org/
version: ${project.version}
commands:
    buy:
        description: Buy goods for sale on the VirtualShop.
        usage: /buy <amount> <item> [maxprice]
    sell:
        description: Put goods up for sale on the VirtualShop.
        usage: /sell <amount> <item> <price> | /sell <amount> hand <price>
    cancel:
        description: Removes items from VirtualShop.
        usage: /cancel <item>
    price:
        description: Find offers for an item.
        usage: /price <item>
    list:
        description: List items for sale.
        usage: /list [player] [page]
    sales:
        description: See sales that have been made.
        usage: /sales [player] [page]
permissions:
    virtualshop.sell:
        description: Allow usage of /sell
        default: true